### ISSUE TITLE
Runtime error: "java.lang.ClassNotFoundException: org.aertslab.grnboost.GRNBoost"

### ISSUE THREAD

**Issue by Sinan81** [aertslab/GRNBoost#2]
I am wondering if there is a quick fix for the below error.
```
user@host $ spark-submit --class org.aertslab.grnboost.GRNBoost --master local[*] --deploy-mode client --jars /home/user/.m2/repository/joda-time/joda-time/2.5/joda-time-2.5.jar /home/user/.m2/repository/ml/dmlc/xgboost4j/0.8-SNAPSHOT/xgboost4j-0.8-SNAPSHOT.jar  /opt/GRNBoost/target/scala-2.11/GRNBoost.jar --version
java.lang.ClassNotFoundException: org.aertslab.grnboost.GRNBoost
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:229)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:695)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by Sinan81** [comment]
dealt with the error by exporting the path to  the "classes" folder, located at the same path as GNRBoost.jar
```
export SPARK_DIST_CLASSPATH=/path/to/GRNBoost/target/scala-2.11/classes:$SPARK_DIST_CLASSPATH
```
Issue can be closed.

**Comment by Sinan81** [comment]
This can be fixed by adding mainclass statement in sbt build file:
```
// assembly config
assemblyJarName := "GRNBoost.jar"
test in assembly := {}
mainClass in assembly := Some("org.aertslab.grnboost.GRNBoost")
```
which also takes care of similar errors for GRNBoost dependencies.
