### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: scopt/OptionParser

### ISSUE THREAD

**Issue by Sinan81** [aertslab/GRNBoost#3]
```
[vagrant@localhost ~]$ spark-submit  --class org.aertslab.grnboost.GRNBoost --master local[*] --deploy-mode client --jars  ~/.m2/repository/ml/dmlc/xgboost4j/0.8-SNAPSHOT/xgboost4j-0.8-SNAPSHOT.jar  /home/vagrant/GRNBoost/target/scala-2.11/GRNBoost.jar --version
Exception in thread "main" java.lang.NoClassDefFoundError: scopt/OptionParser
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.aertslab.grnboost.GRNBoost$.main(GRNBoost.scala:47)
	at org.aertslab.grnboost.GRNBoost.main(GRNBoost.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: scopt.OptionParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
```

**Comment by Sinan81** [comment]
Following https://github.com/sbt/sbt-assembly, added the `mainClass ...` line in 'assembly config' section:
```
// assembly config
assemblyJarName := "GRNBoost.jar"
test in assembly := {}
mainClass in assembly := Some("org.aertslab.grnboost.GRNBoost")
```
 now it seems GRNBoost is finally working
```
[vagrant@localhost ~]$ spark-submit  --class org.aertslab.grnboost.GRNBoost --master local[*] --deploy-mode client --jars ~/.m2/repository/ml/dmlc/xgboost4j/0.8-SNAPSHOT/xgboost4j-0.8-SNAPSHOT.jar  /home/vagrant/GRNBoost/target/scala-2.11/GRNBoost.jar --version
GRNBoost 0.1

GRNBoost
--------
```
